import {defineArrayMember, defineField, defineType} from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site settings',
  type: 'document',
  groups: [
    {name: 'general', title: 'General', default: true},
    {name: 'nav', title: 'Navigation'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'tagline',
      type: 'string',
      group: 'general',
      description: 'Sits beside the wordmark in the footer. One short line.',
    }),
    defineField({
      name: 'githubUrl',
      title: 'GitHub URL',
      type: 'url',
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'priceAmount',
      title: 'Mac price — bought here',
      type: 'number',
      group: 'general',
      initialValue: 2.99,
      description:
        'The direct price, with a licence code. Write {price} in copy to insert it, formatted.',
      validation: (Rule) => Rule.min(0).precision(2),
    }),
    defineField({
      name: 'licenceSeats',
      title: 'Macs per licence code',
      type: 'number',
      group: 'general',
      initialValue: 5,
      description: 'Write {seats} in copy to insert it.',
      validation: (Rule) => Rule.integer().min(1),
    }),
    defineField({
      name: 'appStorePriceAmount',
      title: 'Mac price — Mac App Store',
      type: 'number',
      group: 'general',
      initialValue: 3.99,
      description: 'Write {appStorePrice} in copy to insert it, formatted.',
      validation: (Rule) => Rule.min(0).precision(2),
    }),
    defineField({
      name: 'priceCurrency',
      title: 'Currency',
      type: 'string',
      group: 'general',
      initialValue: 'USD',
      options: {
        list: [
          {title: 'US dollar', value: 'USD'},
          {title: 'Euro', value: 'EUR'},
          {title: 'Danish krone', value: 'DKK'},
          {title: 'British pound', value: 'GBP'},
        ],
      },
    }),
    defineField({
      name: 'downloadUrl',
      title: 'Mac purchase URL — bought here',
      type: 'url',
      group: 'general',
      description:
        'The checkout for the direct, licence-code version. Leave empty until it exists: while empty, the site says the app is on its way instead of showing a dead button.',
    }),
    defineField({
      name: 'macAppStoreUrl',
      title: 'Mac App Store URL',
      type: 'url',
      group: 'general',
      description: 'Leave empty until the listing is live.',
    }),
    defineField({
      name: 'iosAppStoreUrl',
      title: 'iPhone App Store URL',
      type: 'url',
      group: 'general',
      description: 'Leave empty until the iPhone app is live. While empty, the iPhone section says it is in development.',
    }),
    defineField({
      name: 'contactEmail',
      type: 'string',
      group: 'general',
      validation: (Rule) => Rule.required().email(),
    }),
    defineField({
      name: 'navLinks',
      title: 'Header links',
      type: 'array',
      group: 'nav',
      of: [defineArrayMember({type: 'link'})],
      validation: (Rule) => Rule.max(5),
    }),
    defineField({
      name: 'footerLinks',
      title: 'Footer links',
      type: 'array',
      group: 'nav',
      of: [defineArrayMember({type: 'link'})],
    }),
    defineField({
      name: 'footerNote',
      title: 'Footer note',
      type: 'text',
      rows: 3,
      group: 'general',
      description: 'Licence, credits, the small print.',
    }),
    defineField({name: 'seo', type: 'seo', group: 'seo'}),
  ],
  preview: {prepare: () => ({title: 'Site settings'})},
})
